version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media


    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"


  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Shopx worker --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Shopx beat --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db
  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 Shopx.asgi:application
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db
    ports:
      - "8001:8001"

  nginx:
     build:
       context: .
       dockerfile: nginx/Dockerfile
     ports:
       - "80:80"
     volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
     depends_on:
       - web




volumes:
  dbdata:
  static_volume:
  media_volume: