# Generated by Django 5.0 on 2024-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recall",
            name="recall_images",
        ),
        migrations.AddField(
            model_name="recall",
            name="images",
            field=models.ImageField(
                blank=True, null=True, upload_to="recall_image/%Y/%m/%d/"
            ),
        ),
        migrations.DeleteModel(
            name="RecallImages",
        ),
    ]
