# Generated by Django 5.0 on 2024-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_baner", "0002_alter_baner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baner",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
